<?php
if( ! defined('IN_MANAGER_MODE') || IN_MANAGER_MODE !== true) {
    die("<b>INCLUDE_ORDERING_ERROR</b><br /><br />Please use the EVO Content Manager instead of accessing this file directly.");
}
?>

<div class="sectionHeader"><?php echo $_lang['documentation']; ?></div><div class="sectionBody">
    <table border="0" cellspacing="0" cellpadding="0">
        <tr><td><a href="https://docs.evo.im/" target="_blank">What is EVO?</a></td><td></td><td>Official EVO documentation</td></tr>
        <tr><td><a href="https://evo.im/" target="_blank">evo.im</a></td><td></td><td>Home of EVO</td></tr>
        <tr><td><a href="https://forum.evo.im/" target="_blank">EVO Forums</a></td><td></td><td>General support & discussions</td></tr>
        <tr><td><a href="https://docs.evo.im/" target="_blank">docs.evolution-cms.com</a></td><td></td><td>Further documentation</td></tr>
        <tr><td><a href="https://docs.evo.im/03_develop/03_api.html" target="_blank">API Reference</a></td><td></td><td>Further documentation</td></tr>
    </table>
</div>
